/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

import { Dataset, Testimonial, Category } from './types';

export const CATEGORIES: Category[] = [
  { id: 'it', name: 'IT Companies', datasetCount: 120, icon: 'Laptop' },
  { id: 'startups', name: 'Startups', datasetCount: 85, icon: 'Rocket' },
  { id: 'manufacturing', name: 'Manufacturing', datasetCount: 64, icon: 'Factory' },
  { id: 'ecommerce', name: 'E-commerce', datasetCount: 92, icon: 'ShoppingBag' },
  { id: 'healthcare', name: 'Healthcare', datasetCount: 45, icon: 'Stethoscope' },
  { id: 'marketing', name: 'Marketing Agencies', datasetCount: 78, icon: 'Megaphone' },
];

export const MOCK_DATASETS: Dataset[] = [
  {
    id: '1',
    title: 'Kolkata Restaurant Owner Database',
    description: 'Verified contact details of restaurant owners and managers across Kolkata. Perfect for food tech and supply chain businesses.',
    contactCount: 5000,
    industry: 'Food & Beverage',
    category: 'Retail',
    location: 'Kolkata',
    country: 'India',
    companySize: '1-50',
    price: 999,
    fields: ['Name', 'Phone', 'Email', 'Restaurant Name', 'Address'],
    lastUpdated: '2024-03-01',
  },
  {
    id: '2',
    title: 'Bangalore Tech Startup Founders',
    description: 'Direct contact information for founders and C-level executives in Bangalore startups. High-growth companies with recent funding.',
    contactCount: 3500,
    industry: 'Technology',
    category: 'Startups',
    location: 'Bangalore',
    country: 'India',
    companySize: '11-200',
    price: 1499,
    fields: ['Name', 'LinkedIn URL', 'Work Email', 'Company Name', 'Funding Stage'],
    lastUpdated: '2024-02-15',
  },
  {
    id: '3',
    title: 'Mumbai Real Estate Agencies',
    description: 'Comprehensive list of registered real estate agencies and brokers in Mumbai. Includes license numbers and office locations.',
    contactCount: 8000,
    industry: 'Real Estate',
    category: 'Services',
    location: 'Mumbai',
    country: 'India',
    companySize: '1-10',
    price: 1999,
    fields: ['Agency Name', 'Owner Name', 'Contact Number', 'Email', 'License No'],
    lastUpdated: '2024-03-05',
  },
  {
    id: '4',
    title: 'Delhi Manufacturing Units',
    description: 'Database of small to medium manufacturing units in Delhi NCR region. Covers industrial areas like Okhla and Bawana.',
    contactCount: 12000,
    industry: 'Manufacturing',
    category: 'Manufacturing',
    location: 'Delhi',
    country: 'India',
    companySize: '51-500',
    price: 2499,
    fields: ['Company Name', 'Director Name', 'Phone', 'Email', 'Category'],
    lastUpdated: '2024-01-20',
  },
  {
    id: '5',
    title: 'Hyderabad Healthcare Professionals',
    description: 'Contact details of doctors, clinic owners, and hospital administrators in Hyderabad. Verified medical registration numbers.',
    contactCount: 4200,
    industry: 'Healthcare',
    category: 'Healthcare',
    location: 'Hyderabad',
    country: 'India',
    companySize: '1-50',
    price: 1299,
    fields: ['Name', 'Specialization', 'Clinic Name', 'Phone', 'Email'],
    lastUpdated: '2024-02-28',
  },
  {
    id: '6',
    title: 'Chennai Retail Store Owners',
    description: 'Database of retail shop owners in major shopping hubs of Chennai. Includes lifestyle, electronics, and apparel stores.',
    contactCount: 6500,
    industry: 'Retail',
    category: 'Retail',
    location: 'Chennai',
    country: 'India',
    companySize: '1-10',
    price: 899,
    fields: ['Owner Name', 'Shop Name', 'Category', 'Phone', 'Address'],
    lastUpdated: '2024-03-08',
  },
];

export const TESTIMONIALS: Testimonial[] = [
  {
    id: '1',
    name: 'Rahul Sharma',
    role: 'Sales Director',
    company: 'TechFlow Solutions',
    content: 'DataB2B has transformed our outreach strategy. The quality of leads is exceptional and verified.',
    avatar: 'https://picsum.photos/seed/rahul/100/100',
  },
  {
    id: '2',
    name: 'Priya Patel',
    role: 'Marketing Manager',
    company: 'GrowthLabs',
    content: 'Instant downloads and clean data. We saw a 30% increase in our email open rates using their databases.',
    avatar: 'https://picsum.photos/seed/priya/100/100',
  },
  {
    id: '3',
    name: 'Vikram Singh',
    role: 'Founder',
    company: 'Mumbai Ventures',
    content: 'The most reliable source for B2B data in India. Highly recommended for startups looking to scale.',
    avatar: 'https://picsum.photos/seed/vikram/100/100',
  },
];
